### ISSUE TITLE
CodeQl fails since Qt open source download mirror is down

### ISSUE THREAD

**Issue by ann0see** [corrados/jamulus#873]
Qt seems to have severe problems with their download mirror which results in a failiure of our CodeQl action.
https://www.qt.io/blog/problem-with-open-source-downloads

I don't have a good feeling on this since the server has been down for a couple of days now. We could use another mirror:
https://github.com/jurplel/install-qt-action#mirror

Any thoughts on this?

**Comment by corrados** [comment]
I am pretty sure these problems will be solved soon. I assume this is a temporary outage and will not occur very often. So I would stick to the current URL (since it is the official server).

**Comment by ann0see** [comment]
Ok. I hope so. It has already been a few days. So let's wait and see.

**Comment by corrados** [comment]
https://www.qt.io/blog/open-source-downloads-working-again

Should we close this then?

**Comment by ann0see** [comment]
Yes. If it works we can close this issue. Nevertheless, I'm still a bit nervous of this long downtime...

**Comment by pljones** [comment]
Seems to be back?

**Comment by ann0see** [comment]
I will close it. Hopefully it works now.

**Comment by hoffie** [comment]
Seems like there was just a failure when trying the berkeley.edu mirror. The mentioned URL works from my own network, though, so it might be either temporary or it might be routing specific:

https://github.com/corrados/jamulus/runs/1765297586?check_suite_focus=true

```
python -m aqt install 5.15.2 windows desktop win64_msvc2019_64 -O D:\a\jamulus\jamulus/Qt
2021-01-25 22:04:07,201 - aqt - INFO - aqtinstall(aqt) v0.11.1 on Python 3.9.1 [CPython MSC v.1927 64 bit (AMD64)]
Download error: HTTPConnectionPool(host='mirrors.ocf.berkeley.edu', port=80): Read timed out.
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.9.1\x64\lib\site-packages\urllib3\response.py", line 438, in _error_catcher
    yield
  File "C:\hostedtoolcache\windows\Python\3.9.1\x64\lib\site-packages\urllib3\response.py", line 519, in read
    data = self._fp.read(amt) if not fp_closed else b""
  File "C:\hostedtoolcache\windows\Python\3.9.1\x64\lib\http\client.py", line 458, in read
    n = self.readinto(b)
  File "C:\hostedtoolcache\windows\Python\3.9.1\x64\lib\http\client.py", line 502, in readinto
    n = self.fp.readinto(b)
  File "C:\hostedtoolcache\windows\Python\3.9.1\x64\lib\socket.py", line 704, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out
```
